/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Auto_MapFooter: typeof import('./components/Auto_Map/Auto_MapFooter.vue')['default']
    Auto_MapPanel: typeof import('./components/Auto_Map/Auto_MapPanel.vue')['default']
    Auto_WaterFooter: typeof import('./components/Auto_Water/Auto_WaterFooter.vue')['default']
    Auto_WaterPanel: typeof import('./components/Auto_Water/Auto_WaterPanel.vue')['default']
    CameraControl: typeof import('./components/Map/CameraControl.vue')['default']
    Flowerpot: typeof import('./components/Flowerpot.vue')['default']
    Flowerpots: typeof import('./components/Map/Flowerpots.vue')['default']
    GlobalMap: typeof import('./components/Map/GlobalMap.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InitFooter: typeof import('./components/Init/InitFooter.vue')['default']
    InitPanel: typeof import('./components/Init/InitPanel.vue')['default']
    InspectionFooter: typeof import('./components/Inspection/InspectionFooter.vue')['default']
    InspectionPanel: typeof import('./components/Inspection/InspectionPanel.vue')['default']
    LaserScan: typeof import('./components/LaserScan.vue')['default']
    Lidar: typeof import('./components/Map/Lidar.vue')['default']
    Manual_MapFooter: typeof import('./components/Manual_Map/Manual_MapFooter.vue')['default']
    Manual_MapPanel: typeof import('./components/Manual_Map/Manual_MapPanel.vue')['default']
    Map: typeof import('./components/Map/Map.vue')['default']
    Navigation: typeof import('./components/Map/Navigation.vue')['default']
    NavigationPath: typeof import('./components/NavigationPath.vue')['default']
    OperatePanel: typeof import('./components/OperatePanel.vue')['default']
    OperatorPanel: typeof import('./components/OperatorPanel.vue')['default']
    PendingFooter: typeof import('./components/Pending/PendingFooter.vue')['default']
    PendingPanel: typeof import('./components/Pending/PendingPanel.vue')['default']
    PotInfo: typeof import('./components/PotInfo.vue')['default']
    PotList: typeof import('./components/PotList.vue')['default']
    Robot: typeof import('./components/Robot.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TargetFooter: typeof import('./components/Target/TargetFooter.vue')['default']
    TargetPanel: typeof import('./components/Target/TargetPanel.vue')['default']
  }
}
